title: yunbinni 블로그

url: https://just-the-docs.github.io

aux_links:
  "yunbinni의 github": https://github.com/yunbinni

heading_anchors: true

mermaid:
  version: "9.1.6"

# theme: just-the-docs # 로컬환경에서 개발할 때는 전용 yml 파일로 하는 것이 좋다.
# https://github.com/just-the-docs/just-the-docs/issues/148#issuecomment-504761189
remote_theme: just-the-docs/just-the-docs