title: yunbinni 블로그
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/yunbinni

heading_anchors: true

mermaid:
  version: "9.1.3"

remote_theme: just-the-docs/just-the-docs